# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_app', '0002_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
