# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_app', '0003_secret_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='likes',
        ),
    ]
