# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_app', '0004_remove_secret_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.ManyToManyField(related_name='liked_secret', to='secret_app.User'),
        ),
    ]
