# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secret_app', '0005_secret_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_posts', to='secret_app.User'),
            preserve_default=False,
        ),
    ]
